Работяги из Чайхоны.
VK-BMSTU-QA/homework-selenium-2024-spring pull request #13
Opened 2024-05-20 11:25 UTC by Vilinvil

2024-05-20 11:25 UTC, Vilinvil commented
Код ревью друг друга в этих пр-ах:
https://github.com/Vilinvil/homework-4-selenium-2024-spring/pull/2
https://github.com/Vilinvil/homework-4-selenium-2024-spring/pull/1

2024-05-20 20:55 UTC, alexey-ershkov requested changes
Приветы) проблема с паттерном PageObject, ее прям нужно править

2024-05-20 20:55 UTC, alexey-ershkov commented on hw/code/requirements.txt
> +attrs==23.2.0
Это лучше в корень репозитория

2024-05-20 20:55 UTC, alexey-ershkov commented on hw/code/test_budget.py
> +        self.main_page.click(self.main_page.locators.sidebar_locators.BUTTON_BUDGET)
Локаторы не должны протекать в тесты, подобные вещи должны быть реализованы внутри абстракции страницы - это нужно поправить везде

2024-05-20 20:55 UTC, alexey-ershkov commented on hw/code/test_budget.py
> +        # self.budget_page.write_input(self.budget_page.locators.INPUT_AMOUNT_WITHOUT_VAT, '166667')
комментов быть не должно, тоже стоит везде выпилить

2024-05-20 20:55 UTC, alexey-ershkov commented on hw/code/test_footer.py
> +        assert self.base_page.find(self.base_page.locators.FOOTER_WRAPPER_LANGUAGE, until_EC=EC.visibility_of_element_located)
в общем да, все нужно унести в страницу - тесты должны читаться, как будто действия обычного человека, иначе смысла в PageObject паттерне нет

2024-05-21 15:12 UTC, Vilinvil commented on hw/code/requirements.txt
> +attrs==23.2.0
перенес

2024-05-21 15:13 UTC, Vilinvil commented on hw/code/test_budget.py
> +        # self.budget_page.write_input(self.budget_page.locators.INPUT_AMOUNT_WITHOUT_VAT, '166667')
удалил

2024-05-21 15:14 UTC, Vilinvil commented on hw/code/test_footer.py
> +        assert self.base_page.find(self.base_page.locators.FOOTER_WRAPPER_LANGUAGE, until_EC=EC.visibility_of_element_located)
Спидранили, как могли, но пару разделов не успели переписать к рк (monetization_footer, settings)

2024-06-25 09:38 UTC, dkotegov commented
Принято

2024-06-25 09:38 UTC, closed without merging