Umlaut
VK-BMSTU-QA/homework-selenium-2024-spring pull request #3
Opened 2024-05-14 13:11 UTC by Max425

2024-05-14 13:21 UTC, StomaFedor commented
Аппрув

2024-05-14 13:42 UTC, flioletty commented
апрув

2024-05-14 13:46 UTC, wergit13 approved these changes

2024-05-14 13:58 UTC, Max425 commented
апрув

2024-05-14 18:53 UTC, alexey-ershkov requested changes
Приветы, накинул комментов, три основные проблемы, которые очень часто встречаются

- Протекает page object паттерн, локаторы в тесты пролезают и прочее
- Есть огромные локаторы, которые очень легко поломать, это проблема
- Есть слипы в тестах, вместо них нужно использовать ожидание - про стратегии ожидания [тут](https://www.selenium.dev/documentation/webdriver/waits/)

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_audience_page.py
> +    # ElementNotInteractableException: Message: Element <input> could not be scrolled into view
Комменты точно стоит все выпилить

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_audience_page.py
> +        submit_button = audience_page.find(audience_page.locators.MODAL_SUBMIT_BUTTON)
поиск тоже в страницу, в тестах не должно быть локаторов

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_budget_page.py
> +    CORRECT_AMOUNT = 800
что такое correct?))

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_ecomm_page.py
> +        time.sleep(1)
time.sleep нигде быть не должно) антипаттерн, правильнее дожидаться какого-то признака, что что-то появилось/скрылось/пошел запрос и тд. Вот [апи](https://www.selenium.dev/documentation/webdriver/waits/) для этого

Убрать sleep везде

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_ecomm_page.py
> +        ecomm_page.enter_catalog_name('')
Вот тесты хорошие, если слипы убрать, локаторы и прочая информация скрыта внутри страницы. И по сути тест читается так, как будто живой человек вручную тестирует

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_ecomm_page.py
> +
Перенос на новую строку в конце потеряли, проверьте пж везде

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_education.py
> +def vk_pubclic(open_education_modal, education_page):
pupclic -> public?

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/test_main_page.py
> +        assert main_page.find(MainPageLocators.SLIDER_SUBTITLE).text in subtitle
в общем да, везде локаторов в тестах быть не должно

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/ui/locators/ecomm_page_locators.py
> +                           f"//*[contains(@class, 'vkuiFormItem vkuiFormItem--withPadding vkuiInternalFormItem vkuiFormItem--sizeY-none vkuiInternalFormItem--sizeY-none vkuiFormItem--withTop vkuiInte
`FormItem_topText__cD8oZ` - локаторы не должны содержать хеши, при следующей сборке они изменятся и тесты попадают

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/ui/locators/ecomm_page_locators.py
> +                           f"//*[contains(@class, 'vkuiFormItem vkuiFormItem--withPadding vkuiInternalFormItem vkuiFormItem--sizeY-none vkuiInternalFormItem--sizeY-none vkuiFormItem--withTop vkuiInte
Плюс в целом очень большой локатор, надо уменьшать, а то любой класс отсюда удали и тесты упадут

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/ui/locators/ecomm_page_locators.py
> +    CREATE_CATALOG_FINISH_BUTTON = (By.XPATH,
И тут большой локатор, стоит поправить везде и подумать как можно удобнее искать необходимый элемент

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/ui/locators/education_locators.py
> +        return (By.XPATH, f"//*[contains(@class, 'Objects_item') and contains(div/div/div/span, '{label}')]")
`div/div/div/span` - опирается на структуру, антипаттерн, меняется структура и тест падает, поправьте пожалуйста везде

2024-05-14 18:53 UTC, alexey-ershkov commented on hw/code/ui/locators/money_page_locators.py
> +    SITE_BUTTON = (By.XPATH, f"//*[contains(@class, 'Tabs_tab__') and text()='Для сайтов']")
вот пример стабильных локаторов, стоит на них опираться

2024-05-16 09:00 UTC, Max425 commented
![image](https://github.com/VK-BMSTU-QA/homework-selenium-2024-spring/assets/57855981/652851d2-6190-4cd8-baee-f0d2f985a8d5)

2024-05-19 15:11 UTC, alexey-ershkov requested changes
Приветы) молодцы, практически все поправили, написал еще немного комментов

2024-05-19 15:11 UTC, alexey-ershkov commented on hw/code/test_audience_page.py
> +        time.sleep(1)   # sleep это часть теста
Вот тут нужно обоснование поподробнее - почему не можете использовать ожидание какого-то элемента на странице?

2024-05-19 15:11 UTC, alexey-ershkov commented on hw/code/test_budget_page.py
> +        assert self.AMOUNT_FIELD_TITLE in self.driver.page_source
Вот такие ассерты очень общие - они просто проверяют в составе страницы что-то есть. Лучше проверять именно в конкретном элементе. В случае изменения места, где находится текст - тест должен это подсвечивать

Вижу, что такие ассерты есть и ниже - посмотрите пж везде и поправьте

2024-05-19 15:11 UTC, alexey-ershkov commented on hw/code/test_budget_page.py
> +    def test_correct_amount(self, budget_page):
`test_correct_amount` - название не отражает суть теста, в чем корректность, вижу тоже ниже есть, посмотрите пж везде и поправьте

2024-05-19 15:11 UTC, alexey-ershkov commented on hw/code/test_ecomm_page.py
> +        self.wait.until(lambda d: ecomm_page.is_education_modal_closed())
Молодцы, лайк)

2024-05-19 15:11 UTC, alexey-ershkov commented on hw/code/test_budget_page.py
> +    MIN_AMOUNT_WITHOUT_VAT = 500
У вас в части тестов в self хранятся тексты, а где-то по месту, приведите пожалуйста к единому виду

2024-05-19 15:11 UTC, alexey-ershkov commented on hw/code/test_education.py
> +        education_page.is_visible(education_page.locators.VK_PUBLIC_MODAL)
У вас все еще локаторы в тестах есть - их быть не должно, test_ecom_page и test_audience_page прям хорошо сделаны, ориентируйтесь на них 

Посмотрите пж везде, что локаторы не прорастают в тесты, они должны быть в page, иначе паттерн pageObject нарушается

2024-05-19 18:20 UTC, alexey-ershkov approved these changes
Аппрув

2024-06-25 08:57 UTC, dkotegov commented on hw/code/test_company_page.py
> +    time.sleep(3)  # тут нужно время для загрузки фото
sleep в тестах это антипаттерн, во время слипов тесты ничего не делают
вместо них надо использовать wait и expected conditions

2024-06-25 08:57 UTC, dkotegov commented on hw/code/ui/pages/audience_page.py
> +        time.sleep(2)
И тут

2024-06-25 08:58 UTC, dkotegov commented on hw/code/ui/pages/ecomm_page.py
> +        #self.click(self.locators.CREATE_CATALOG_FINISH_BUTTON)
Закоменченный код надо убрать

2024-06-25 09:33 UTC, dkotegov commented
Ладно

2024-06-25 09:33 UTC, closed without merging